### PR TITLE
Removed TBB library.  

### PR DESCRIPTION
**Pull request by namreeb**
If anyone has any evidence as to why this is useful, we can re-visit it then.

Note that no objections were raised on the forum thread (located here: http://cmangos.net/thread-7192.html) for the past month.

### CODE REVIEW

**Comment by VladimirMangos** [comment]
As I remember it mostly help at Unix side.... but can be wrong in memory.

**Comment by namreeb** [comment]
It surely will reduce memory fragmentation, but so will some very basic pre-allocation.  It doesn't justify such a large third party API.  If there are some problems that appear as a result of this, we can consider other, simpler solutions.

**Comment by sanctum32** [comment]
Core entirely doesn't use it at all... I didn't seen any calls of this library in core code. In pervious mangos experience I removed it and didn't seen any change in performance, memory usage.

**Comment by namreeb** [comment]
It used the allocator, I believe.  But it did not use the custom containers.

**Comment by zergtmn** [comment]
Iirc at the time it was added by @Ambal TBB allocator was much faster than standard allocator on Windows and slightly faster on linux. This might still be the case but I have no up-to-date information on this matter.

**Comment by FallenAngelX** [comment]
https://github.com/cmangos/mangos-wotlk/blob/master/src/framework/Policies/MemoryManagement.cpp

**Comment by namreeb** [comment]
I think there is no question that it is faster in almost call cases, sometimes more than twice as fast.  I'm just not sure that we need it?  It seems like an over optimization, and we will regain any overall performance lost once we implement per-map threading.

**Comment by Ambal** [comment]
I added TBB library in order to utilize memory allocator + we wanted to reuse some threading primitives and thread-safe containers.

**Comment by namreeb** [comment]
Closing this for now as it requires some benchmarking, analysis, etc..

**Pull request closed without merging**
