### PR TITLE
Miscellaneous code cleanups.  Sorry for the large commit but there should be no functional changes here.

### PR DESCRIPTION
**Pull request by namreeb**
I am submitting this via PR to give people a chance to object.  Please note that this was exceptionally tedious, so please do not ask that it be broken up into small commits.  There should be no functional change as a result of this commit to surprise anyone.

### CODE REVIEW

**Comment by stfx** [comment]
👍 only missing whitespaces before static keyword changes and should we really use exceptions?

**Comment by namreeb** [comment]
Why not use exceptions?

**Comment by killerwife** [comment]
I think using exceptions in cmangos code is a divergence from code style used. We usually handle code without them. I think thats what @stfx was trying to say.

**Comment by namreeb** [comment]
Okay well I can replace them with asserts since it's probably a topic for another discussion.  Incidentally, we do use exceptions already.  I don't see any reason why our style is benefited by discarding them.

**Comment by killerwife** [comment]
Maybe in netcode/lower levels, but in general mechanics code, I have yet to see it.

**Comment by cyberium** [comment]
👍  about throw exception its ok, its true that we used to use assert/MANGOS_ASSERT but it dont realy hurt to see that in code produced in 2016.

btw i wonder how you decided what method should be const or not there is for sure much case to handle.

**Comment by namreeb** [comment]
I made const those functions which should not alter the state of their objects. I'm sure I missed some and there are some which could technically be made const but I left them since they do alter state.

**Pull request merged**
