### PR TITLE
Require ToTP Token for Accounts at or above a gmlevel

### PR DESCRIPTION
**Pull request by JerbAcuch**
* Added new feature that allows the option to require a token for accounts of a specific gmlevel and higher, including all accounts. Enforced by prompting for token, regardless if one is in the DB

## 🍰 Pullrequest
Edits realmd.conf.dist.in and src/realmd/AuthSocket.cpp; creates a new realmd variable "RequireTokensFor" which takes the gmlevel and will force characters of that level and higher to use a token. Implemented by simply showing the token regardless if one is set or not.

No obvious error messages existed in the client to help achieve this so simply showing the token box seemed like the right answer.

### Proof
- None

### Issues
- None

### How2Test
* Configure realmd.conf "RequireTokensFor" to -1, attempt to log into a player and an admin, no token box will appear.
* Configure realmd.conf "RequireTokensFor" to 0, attempt to log into a player account and a token box will appear.
* Configure realmd.conf "RequireTokensFor" to 1, attempt to log in with a player character and no token box will appear.
* Configure realmd.conf "RequireTokensFor" to 1, attempt to log in with a game master or above and token box will appear.

### Todo / Checklist

- [X] None

### CODE REVIEW

**Comment by al3xc1985** [comment]
Nice. Ty

**Comment by JerbAcuch** [comment]
Text modification recommendation to validate edge cases:

* Configure realmd.conf "RequireTokensFor" to 0, attempt to log into a player acount and a token box will appear.
* Configure realmd.conf "RequireTokensFor" to 1, attempt to log in with a player character and no box will appear.
* Configure realmd.conf "RequireTokensFor" to 1, attempt to log in with a game master or above and token box will appear.

**Comment by killerwife** [comment]
I am not opposed to this change. I will think on it whether I can think of any downside/problem, but otherwise you can expect this to get merged very soon.

**Comment by JerbAcuch** [comment]
Just code reviewed this for fun and realized it may not default disabled… hold please.

**Comment by JerbAcuch** [comment]
I apparently don't know how to git, so had to force push... but tested this for disable and now works.

**Comment by al3xc1985** [comment]
why close?

**Comment by killerwife** [comment]
He pushed commit inside it by mistake and doesnt know how to fix it would be my guess

**Comment by JerbAcuch** [comment]
Hahah. Yeah, I spent a lot of time fixing it and then at the end somehow merged it all back in anyway. I’m new to git and I’ll just cherry pick the two required commits and resend.  Hell, I didn’t realize you had to keep a branch open on a push request and closed it that way once too hah.

Sorry for the idiocy.

**Comment by al3xc1985** [comment]
U forget to open a new one

**Comment by al3xc1985** [comment]
@killerwife do u still have this on your radar? cause it was never reopened

**Pull request closed without merging**
