### PR TITLE
Add Berserk condition after 100 stacks SPELL Mark.

### PR DESCRIPTION
**Pull request by Ulduar**
Also avoid berserk spam.

### CODE REVIEW

**Comment by xfurry** [comment]
I don't really understand what is this change supposed to do.
Can you please explain why do we need it, in more details.

**Comment by Ulduar** [comment]
Hello @xfurry 
https://github.com/cmangos/mangos-wotlk/pull/250/files#diff-3aafe9716c7304e804e663f51a1ed42aR64
``` CPP
I don't really understand what is this change supposed to do.
Can you please explain why do we need it, in more details.
```

 // Note: Berserk should be applied once 100 marks are casted.

**Comment by xfurry** [comment]
Ok, but is Berserk really cast after 100 stacks?
I thought that the stacks themselves server as the Berserk mechanics.

**Comment by xfurry** [comment]
Poke @killerwife as you are the Naxx expert.
Should we cast Berserk after 100 stacks?

**Comment by cala** [comment]
I'm not an expert of the WotLK version but I've done Naxxramas several times in Classic and TBC so yes, hitting the 100 marks was like the end of the encounter : in Classic/TBC the Horsemen would enrage and start using their abilities whitout cooldowns. In WotLK they would go berserk and have their damage significantly increased (x1000% o_O).

**Comment by killerwife** [comment]
@xfurry I have no idea. Actually naxx is one of my weak spots, I never saw it in vanilla, and in wotlk it was so easy you didn't notice any of these mechanics.

**Comment by cyberium** [comment]
Sound correct should we have to merge it? @xfurry maybe @Grz3s also.

**Comment by cala** [comment]
I will deal with this (WotLK code and the Classic version).

**Comment by cala** [comment]
The Classic version of this enrage is already in Classic & TBC core but needs some testing (I'm doing it atm). It is also done differently from this PR so I'll update either the PR or the two other cores for consistency.

**Comment by cala** [comment]
Merged in https://github.com/cmangos/mangos-wotlk/commit/810bb8b2c6efc4caa55306dba1bee588e8bd8556 :+1:

**Pull request closed without merging**
