### PR TITLE
Enable high-res extraction in ExtractResources.sh

### PR DESCRIPTION
**Pull request by Muehe**
See https://github.com/cmangos/issues/issues/1877 for related discussion.

* Changed shebang to point to `sh` instead of `bash` across all versions
* Added changes by @adellaci to enable high-res extraction
* Changed description of two user inputs to include the expected options

### CODE REVIEW

**Comment by adellaci** [comment]
@Muehe 
when i run this I still get the error 
```
Ok, all done
Fri Feb 15 20:44:15 EST 2019: Assembling of vmaps finished


sh: 0: Can't open MoveMapGen.sh
```

**Comment by adellaci** [comment]
I'm unable to make it run right without use MoveMapGen8Core.sh script

**Comment by Muehe** [comment]
Hmm, that sound weird, everything was working fine for me. Are you sure you copied both scripts and all the binaries correctly? There should be one binary called `MoveMapGen` and one script called `MoveMapGen.sh`.

**Comment by adellaci** [comment]
@Muehe 
I did a pull this morning, and compiled the latest WotLK /w extractor tools enabled. When i when to the directory ~/build-wotlk/contrib/mmap i have a file 'MapMoveGen' but no 'MapMoveGen.sh'

**Comment by adellaci** [comment]
@Muehe 
NV....i was looking in wrong directory. I found it in ./mangos-wotlk/contrib.extractor_scripts.

**Comment by adellaci** [comment]
Tested compiling result

```
Tue Feb 19 18:52:59 EST 2019
 cmake ~/mangos/mangos-wotlk -DCMAKE_INSTALL_PREFIX=~/wow-servers/mangos-server-wotlk -DBUILD_EXTRACTORS=ON -DBUILD_PLAYERBOT=ON -DPCH=1 -DDEBUG=0 -DBUILD_RECASTDEMOMOD=ON
-- Configuring done
-- Generating done
Tue Feb 19 18:53:04 EST 2019
```
```
Tue Feb 19 19:00:12 EST 2019
make -j12
.....
[100%] Linking CXX executable mangosd
[100%] Built target mangosd
mangos@ubuntu-server-2:~/build-wotlk$ date
Tue Feb 19 19:08:03 EST 2019
```

**Comment by adellaci** [comment]
ExtractResoures.sh with high resolution on both ad and vmaps results from log
```
Sun Feb 17 11:14:26 EST 2019: Start extracting dataz for MaNGOS
DBC and map files will be extracted
Vmaps will be extracted
Mmaps will be extracted with 8 processes

Sun Feb 17 11:14:26 EST 2019: Start extraction of DBCs and map files...
Sun Feb 17 11:15:21 EST 2019: Extracting of DBCs and map files finished

Sun Feb 17 11:15:21 EST 2019: Start extraction of vmaps...
Sun Feb 17 11:16:36 EST 2019: Extracting of vmaps finished
Sun Feb 17 11:16:36 EST 2019: Start assembling of vmaps...
Sun Feb 17 11:16:48 EST 2019: Assembling of vmaps finished

Sun Feb 17 11:16:48 EST 2019: Start creating MoveMaps
Used params: --silent --offMeshInput offmesh.txt
Detailed log can be found in MaNGOSExtractor_detailed.log

Sun Feb 17 12:03:39 EST 2019: Finished creating MoveMaps
Sun Feb 17 12:03:39 EST 2019: Finished creating MoveMaps
```

**Comment by Muehe** [comment]
@cala Any objections to me merging these PRs across all the repos? Cyberium gave me push access so I can do it myself, just asking you first because depending on which repo you used to test the last PR (#263) the outcome for this one may differ due to the whole `sh` vs. `bash` situation (right now wotlk uses the former, classic and tbc the latter).

I don't anticipate any problems either way, but if you want to test again first I'll wait.

**Comment by cala** [comment]
@Muehe hi, to be honest I paid little attention to these PRs and related fixes/issues. I will try to be on discord this afternoon or this evening (western Europe time), so you can enlighten me on these if you are ok.

**Comment by cala** [comment]
@Muehe and... it's a GO from me. Thank you and @adellaci for you work!

**Pull request closed without merging**
