### PR TITLE
Fixed crash in instance resetting code in MapPersistentStateManager::_ResetOrWarnAll

### PR DESCRIPTION
**Pull request by namreeb**
DungeonPersistentState::UnbindThisState calls Player::UnbindInstance
Which calls DungeonPersistentState::RemovePlayer
Which calls MapPersistentState::UnloadIfEmpty
Which calls MapPersistentStateManager::RemovePersistentState.

MapPersistentStateManager::RemovePersistentState modifies the m_instanceSaveByInstanceId collection being iterated over in MapPersistentStateManager::_ResetOrWarnAll

Though perhaps it is cleaner to update the iterator upon removal, it would be a much more drastic change, and I think ultimately not as clean.

I am submitting this via pull request to give people an opportunity to review it.

### CODE REVIEW

**Comment by Kelzior** [comment]
Confirmed and working perfectly! No more crashes anymore when unbinding. Thanks

**Comment by VladimirMangos** [comment]
Nice catch and fix!

**Comment by namreeb** [comment]
I do not think a comment explaining this is necessary.  Everyone should know that you cannot modify a collection while iterating over it in this way.  However I will plan to add a brief explanation.

**Comment by stfx** [comment]
I agree with @VladimirMangos

**Comment by cyberium** [comment]
Yes nice catch i tough i was fixed that a year ago.

**Comment by Kelzior** [comment]
I did report this some months ago but noone even replied then I contacted namreeb and he fixed it in 2mins

**Comment by namreeb** [comment]
The comment has been added.  Merged.

**Pull request merged**
