### PR TITLE
Ymirjar Deathbringer (ICC version, not Pit of Saron).

### PR DESCRIPTION
**Pull request by Ulduar**
http://www.wowhead.com/npc=38125/ymirjar-deathbringer
http://www.wowhead.com/spell=71303/summon-ymirjar
Should cast spell 71302 five times. Or only in 25 man 5 times (if i am not wrong, npc have EAI script in ACID.)
Maybe on 10 normal and 10 heroic should summon 2 ymirjar minion after cast spell, and on 25 normal and 25 heroic - 5 minion. Sorry, cannot remember.

### CODE REVIEW

**Comment by Ulduar** [comment]
Or we can have this variant:

``` CPP
enum
{
  SPELL_SUMMON_YMIRJAR        = 71303,
  NPC_YMIRJAR_DEATHBRINGER    = 38125,
};

bool EffectDummyCreature_spell_spectral_realm_notify(Unit* pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature* pCreatureTarget, ObjectGuid /*originalCasterGuid*/)
{
    if (uiSpellId == SPELL_SUMMON_YMIRJAR && uiEffIndex == EFFECT_INDEX_0 && pCreatureTarget->GetEntry() == NPC_YMIRJAR_DEATHBRINGER)
    {
        if (pCaster->GetTypeId() == TYPEID_PLAYER)
            pCreatureTarget->AI()->SendAIEvent(AI_EVENT_CUSTOM_EVENTAI_A, pCreatureTarget, pCreatureTarget);

        return true;
    }

    return true;
}
'''
And handle on EAI. 10 man normal and heroic - two times cast 71302.
25 man and heroic - five times cast 71302.
Or start db_scripts_on_relay.

**Comment by xfurry** [comment]
Does this summon the same creature five times?

**Comment by Ulduar** [comment]
Hi @xfurry 
Yes, 2 vargul zombie in 10 man, 5 vargul zombie in 25 man should be summoned with this spell.

**Comment by cyberium** [comment]
@xfurry or @Grz3s please don't let that sleep too much.

**Pull request closed without merging**
