### PR TITLE
SafeLoc: Implement Westfall GY as fallback graveyard

### PR DESCRIPTION
**Pull request by insunaa**
## 🍰 Pullrequest

This PR ensures that if no GY can be found for a given character, Westfall is chosen.

### CODE REVIEW

**Comment by Redbu11dev** [comment]
maybe is not very good to have westfall as fallback for both teams? maybe make it westfall only for alliance, and something else for horde?

**Comment by insunaa** [comment]
Unfortunately that is how it is on the reference servers. Both factions always get sent to Westfall when no valid gy can be determined

**Comment by insunaa** [comment]
ok I've added crossroads for horde, pending confirmation that this was how it actually worked in WotLK. From my memory it always used to be Sentinel Hill, and my guess was that Crossroads was added for Horde in a later expansion, but because I don't currently have confirmation either way I added it.

If Team is not Horde it will always to go Sentinel Hill, but if team is definitely Horde then it's going to Crossroads

**Comment by Redbu11dev** [comment]
nice 👍

**Pull request merged**
