### PR TITLE
Updated to OpenSSL 1.0.2f

### PR DESCRIPTION
**Pull request by namreeb**
@xfurry This is the commit I'd like you to test in Visual Studio 2013.

### CODE REVIEW

**Comment by xfurry** [comment]
Not looking very good:

```
Error	1	error C1083: Cannot open include file: 'boost/asio.hpp': No such file or directory (..\..\src\shared\Network\NetworkThread.cpp)	c:\...\temp_test_core\mangos-wotlk\src\shared\network\NetworkThread.hpp	29	1	shared
Warning	2	warning C4018: '<' : signed/unsigned mismatch	C:...\temp_test_core\mangos-wotlk\src\shared\Network\PacketBuffer.cpp	45	1	shared
Error	3	error C1083: Cannot open include file: 'boost/asio.hpp': No such file or directory	C:\...\temp_test_core\mangos-wotlk\src\shared\Network\Socket.cpp	24	1	shared
Error	4	error C1083: Cannot open include file: 'boost/asio.hpp': No such file or directory	C:\...\temp_test_core\mangos-wotlk\src\shared\Network\Socket.hpp	27	1	game
Error	5	error C2664: 'std::atomic_bool::atomic_bool(const std::atomic_bool &)' : cannot convert argument 1 from 'bool' to 'const std::atomic_bool &' (..\..\src\realmd\Main.cpp)	c:\...\temp_test_core\mangos-wotlk\src\shared\network\NetworkThread.hpp	63	1	realmd
Error	6	error C2664: 'std::atomic_bool::atomic_bool(const std::atomic_bool &)' : cannot convert argument 1 from 'bool' to 'const std::atomic_bool &' (..\..\src\mangosd\Master.cpp)	c:\...\temp_test_core\mangos-wotlk\src\shared\network\NetworkThread.hpp	63	1	mangosd
Error	7	error C1083: Cannot open include file: 'boost/asio.hpp': No such file or directory	C:\...\temp_test_core\mangos-wotlk\src\shared\Network\Socket.hpp	27	1	ScriptDev2
```

**Comment by namreeb** [comment]
It looks like something might be wrong with your boost installation.  The compile is working fine for me and fine on travis.  Can you confirm manually that you have %BOOST_ROOT%\boost\asio.hpp?  If you don't, your boost installation is incorrect/incomplete.

**Comment by xfurry** [comment]
I have boost 1.5.9 installed and everything worked fine until https://github.com/cmangos/mangos-wotlk/commit/aebe5ad62290c568ab0884db6a1e50a2523f89d8
I didn't update master to the latest commits, but I suppose I will have the same error as here.

The BOOST_ROOT variable is set and it works just fine. I also checked for asio.hpp file and it's there.

**Comment by namreeb** [comment]
Okay.  I think the problem then is that the shared project doesn't have BOOST_ROOT as an include directory.  I will push a commit for that to the main repo and update this pull request.

**Comment by namreeb** [comment]
I have rebased the PR off of the root fork to which I just pushed a fix for this issue.

**Comment by xfurry** [comment]
Still doesn't work :cry: 
```
Error	1	error C1083: Cannot open include file: 'boost/asio.hpp': No such file or directory	C:\...\Cmangos\workcore-wotlk\src\shared\Network\Socket.hpp	27	1	game
Error	2	error C2664: 'std::atomic_bool::atomic_bool(const std::atomic_bool &)' : cannot convert argument 1 from 'bool' to 'const std::atomic_bool &' (..\..\src\realmd\Main.cpp)	c:\...\cmangos\workcore-wotlk\src\shared\network\NetworkThread.hpp	63	1	realmd
Error	3	error C2664: 'std::atomic_bool::atomic_bool(const std::atomic_bool &)' : cannot convert argument 1 from 'bool' to 'const std::atomic_bool &' (..\..\src\mangosd\Master.cpp)	c:\...\cmangos\workcore-wotlk\src\shared\network\NetworkThread.hpp	63	1	mangosd
```

I have the variable set as BOOST_ROOT with path C:\local\boost_1_59_0\;
And the asio.hpp file is found under C:\local\boost_1_59_0\boost\ folder

**Comment by namreeb** [comment]
My mistake. The boost path must be added to the game library too. I will plan to post back here when that is done.

**Comment by xfurry** [comment]
I updated master and added you workaround for VS2013 and now I have this:

```
Warning	1	warning C4018: '<' : signed/unsigned mismatch	C:\...\Cmangos\workcore-wotlk\src\shared\Network\Socket.cpp	264	1	shared
Warning	2	warning C4018: '<' : signed/unsigned mismatch	C:\...\Cmangos\workcore-wotlk\src\shared\Network\Socket.cpp	277	1	shared
Warning	3	warning C4018: '<' : signed/unsigned mismatch (..\..\src\realmd\Main.cpp)	C:\...\Cmangos\workcore-wotlk\src\shared\Network\Listener.hpp	50	1	realmd
Error	4	error LNK1104: cannot open file 'libboost_system-vc120-mt-1_59.lib'	C:\...\Cmangos\workcore-wotlk\win\VC120\LINK	realmd
Warning	5	warning C4018: '<' : signed/unsigned mismatch (..\..\src\mangosd\Master.cpp)	C:\...\Cmangos\workcore-wotlk\src\shared\Network\Listener.hpp	50	1	mangosd
Error	6	error LNK1104: cannot open file 'libboost_system-vc120-mt-1_59.lib'	C:\...\Cmangos\workcore-wotlk\win\VC120\LINK	mangosd
```

**Comment by namreeb** [comment]
Okay.  Have you compiled both the 64 and 32 bit binaries for the boost libraries?  In what folders are they, relative to $BOOST_ROOT?

**Comment by xfurry** [comment]
Well, first I realized that I had a wrong version of boost. I was using 1.59 win 32 for VC140. So I installed Boost 1.60 win 32 for VC120 and repointed the BOOST_ROOT variable.
The libraries are already include din the installed, so there is no need to build them.
The libboost_system-vc120-mt-1_60.lib is located under ```$BOOST_ROOT\lib32-msvc-12.0\``` folder.
However I still get the same error...

**Comment by namreeb** [comment]
The problem is that there is no standard path for the binaries in Windows.  This is why my suggestion for how to configure your environment is with property sheets.  You can add $(BOOST_ROOT)\lib32-msvc-12.0 to your library include path and it will compile, but that does not solve the general case.  I myself have the boost libs in stage\lib32 and stage\lib64, but that is not standard either.

**Comment by namreeb** [comment]
Since how to solve this issues has wider implications, I have created a thread on the forums so that our discussion is more visible.  Please see here: http://cmangos.net/newthread.php?fid=8&processed=1

Since the openssl part of this pull request is not causing you any issues, I have merged it.

**Pull request merged**
