### PR TITLE
Scripts: Implement EAI vehicle hooks

### PR DESCRIPTION
**Pull request by insunaa**
## 🍰 Pullrequest

I have no idea what I'm doing.

### Todo / Checklist

- [ ] Basic sanity check. I have no idea about EAI

### CODE REVIEW

**Comment by killerwife** [comment]
Do them all while ur at it.

image

**Comment by insunaa** [comment]
`OnVehicleRide` and `OnVehicleAbandon` are basically the same with flipped boarded flag
same with `OnPassengerRide` and `OnPassengerAbandon`
should I nevertheless implement them separately?
Not sure how to approach OnPassengerControlEnd, since I don't know what that entails

**Comment by killerwife** [comment]
Search for SEAT_FLAG_CAN_CONTROL

**Comment by killerwife** [comment]
When he is leaving the seat that gives control.

**Comment by insunaa** [comment]
Alright, I'll see if I can add that

**Comment by insunaa** [comment]
I don't see if I'm still missing something. If you think it's merge-able I'll squash

**Comment by killerwife** [comment]
Works, squash it into one commit, ill resolve pushing to tbc and vanilla per reserving enum later.

**Comment by insunaa** [comment]
squashed

**Pull request merged**
